blank_issues_enabled: false
contact_links:
  - name: "\U0001F4AC Ask a question"
    url: https://github.com/your-org/admin-web/discussions
    about: Start a discussion for general questions or help.
